import { app } from "./firebase-config.js";
import {
  getAuth,
  multiFactor,
  onAuthStateChanged,
  signOut,
  TotpMultiFactorGenerator
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-auth.js";
import {
  getFirestore
} from "https://www.gstatic.com/firebasejs/10.7.1/firebase-firestore.js";
import { resolveUserRole, syncUserRole } from "./role-utils.js";
import { clearAdminMfaSession } from "./admin-mfa-session.js";
import { clearSuperAdminMfaSession } from "./super-admin-mfa-session.js";
import { hasTotpFactor } from "./firebase-native-mfa.js";
import { renderQrSvgDataUri } from "./local-qr.js";

const auth = getAuth(app);
const db = getFirestore(app);

let currentUser = null;
let pendingTotpSecret = null;

function setStatus(message, isError = false) {
  const status = document.getElementById("mfaStatus");
  if (!status) return;
  status.textContent = message;
  status.style.color = isError ? "#ff97b6" : "#8ef7cf";
}

function showSetupUi(email) {
  document.getElementById("setupPanel").hidden = false;
  document.getElementById("verifyPanel").hidden = true;
  document.getElementById("mfaForm").hidden = false;
  document.getElementById("mfaTitle").textContent = "Set Up Admin 2FA";
  document.getElementById("mfaSubtitle").textContent = "Before you can use admin controls, connect an authenticator app and verify one code.";
  document.getElementById("mfaAccountLabel").textContent = `Code Recall (${email || "admin"})`;
  document.getElementById("backupCodeList").innerHTML = "<div class=\"backup-code-chip\">Managed by Firebase Auth</div>";
  updateRecoveryNotice(false);
}

function showAlreadyEnrolledUi() {
  document.getElementById("setupPanel").hidden = true;
  document.getElementById("verifyPanel").hidden = false;
  document.getElementById("mfaForm").hidden = true;
  document.getElementById("mfaTitle").textContent = "Admin 2FA Is Enabled";
  document.getElementById("mfaSubtitle").textContent = "Sign in again and Firebase will ask for your authenticator code before privileged access opens.";
  updateRecoveryNotice(true);
  setStatus("2FA is already enrolled. Log out, then sign in again to trigger the second-factor check.");
}

function updateRecoveryNotice(enrolled) {
  const notice = document.getElementById("mfaRecoveryNotice");
  if (!notice) return;
  notice.textContent = enrolled
    ? "Recovery and factor management are handled in Firebase Auth."
    : "After enrollment, privileged sign-ins require the current code from your authenticator app.";
  notice.style.color = "#8ef7cf";
}

async function prepareEnrollment(user) {
  showSetupUi(user.email || "");
  const session = await multiFactor(user).getSession();
  pendingTotpSecret = await TotpMultiFactorGenerator.generateSecret(session);
  const setupUri = pendingTotpSecret.generateQrCodeUrl(user.email || user.uid, "Code Recall");

  document.getElementById("mfaSecretValue").textContent = pendingTotpSecret.secretKey;
  const qrImage = document.getElementById("mfaQrImage");
  if (qrImage) {
    qrImage.src = renderQrSvgDataUri(setupUri, 220);
  }
  window.currentMfaSetupUri = setupUri;
}

async function completeEnrollment(code) {
  if (!pendingTotpSecret) {
    setStatus("2FA setup is not ready yet. Refresh and try again.", true);
    return;
  }

  const assertion = TotpMultiFactorGenerator.assertionForEnrollment(pendingTotpSecret, code);
  await multiFactor(currentUser).enroll(assertion, "Code Recall Admin");
  clearAdminMfaSession();
  setStatus("Admin 2FA is now enabled. Please sign in again to verify with your authenticator code.");
  window.setTimeout(async () => {
    await signOut(auth);
    window.location.replace("auth.html");
  }, 900);
}

document.getElementById("mfaForm")?.addEventListener("submit", async (event) => {
  event.preventDefault();
  const input = document.getElementById("mfaCodeInput");
  const code = input?.value?.trim() || "";

  if (!code) {
    setStatus("Enter the 6-digit code before continuing.", true);
    return;
  }

  const button = document.getElementById("mfaSubmitBtn");
  if (button) {
    button.disabled = true;
    button.textContent = "Checking...";
  }

  try {
    await completeEnrollment(code);
  } catch (error) {
    console.error("Admin MFA enrollment failed.", error);
    setStatus("Unable to enroll 2FA. Use the current authenticator code and try again.", true);
  } finally {
    if (button) {
      button.disabled = false;
      button.textContent = "Verify and Continue";
    }
  }
});

window.copyMfaSecret = async function() {
  if (!pendingTotpSecret?.secretKey) return;
  await navigator.clipboard.writeText(pendingTotpSecret.secretKey);
  setStatus("Authenticator key copied.");
};

window.copyBackupCodes = async function() {
  await navigator.clipboard.writeText("Recovery is managed through Firebase Auth for this account.");
  setStatus("Recovery note copied.");
};

window.downloadBackupCodes = function() {
  setStatus("Backup codes are not generated by this app. Manage recovery through Firebase Auth.");
};

window.copyMfaSetupLink = async function() {
  if (!window.currentMfaSetupUri) return;
  await navigator.clipboard.writeText(window.currentMfaSetupUri);
  setStatus("Authenticator setup link copied.");
};

window.openAuthenticatorApp = function() {
  if (!window.currentMfaSetupUri) return;
  window.location.href = window.currentMfaSetupUri;
};

window.resetCurrentMfaEnrollment = function() {
  setStatus("Firebase Auth MFA factors must be reset from Firebase Console or Admin SDK.", true);
};

window.logoutMfa = async function() {
  clearAdminMfaSession();
  await signOut(auth);
  window.location.replace("auth.html");
};

onAuthStateChanged(auth, async (user) => {
  if (!user) {
    window.location.replace("auth.html");
    return;
  }

  currentUser = user;
  const role = await resolveUserRole(db, user);
  await syncUserRole(db, user, role);

  if (role === "super_admin") {
    clearAdminMfaSession();
    window.location.replace("super-admin-mfa.html");
    return;
  }

  if (role !== "admin") {
    window.location.replace("dashboard.html");
    return;
  }

  if (hasTotpFactor(user)) {
    showAlreadyEnrolledUi();
    return;
  }

  await prepareEnrollment(user);
});
